flowchart BT
  MP[Market Prices<br/>prix ingredients] --> CP[Components<br/>sous-recettes: pain, steak, sauce]
  CP --> MIT[Menu Items<br/>produit fini: Burger]
  MIT --> SM[Space Menus<br/>quel item dans quelle boutique]
  SM --> PR[Prix specifique par space]
